remodified changes to joint.hpp and rover_arm_system.hpp in correctin…
SJSURoboticsTeam/urc-control_systems-2021 pull request #106
Opened 2022-01-14 20:31 UTC by tbejaoui1

changeg void SetSpeed to void SetJointSpeed in joint.hpp and reflected changes in rover_arm_system.hpp

2022-01-14 21:13 UTC, acarrou commented
Good job, we'll need to change the test function name as well since you renamed the function in the joint class.

2022-01-14 21:13 UTC, acarrou approved these changes

2022-01-14 21:21 UTC, acarrou requested changes
Change Test file function names

2022-01-14 22:20 UTC, naterpotatoers requested changes
fix old failing tests in Arm/test/joint_test.cpp

2022-01-15 06:03 UTC, naterpotatoers approved these changes

2022-01-15 06:03 UTC, acarrou approved these changes

2022-01-15 06:05 UTC, merged