Encoder position
SJSURoboticsTeam/urc-control_systems-2021 pull request #109
Opened 2022-01-15 21:32 UTC by acarrou

just simple encoder position testing.

2022-01-17 01:22 UTC, naterpotatoers requested changes
I think we should just print out all the encoder positions for left, right, and back wheels since we'll need to do that at some point

2022-01-17 01:22 UTC, naterpotatoers commented on Drive/rover_drive_system.hpp
> +    printf("Encoder Position:\t%d\n", right_wheel_.GetSteerEncoderPos());
```suggestion
```
maybe we should move this to the Wheel class Print() function

2022-01-17 01:22 UTC, naterpotatoers commented on Drive/wheel.hpp
> +int GetSteerEncoderPos()
```suggestion
int GetSteerEncoderPosition()
```

2022-01-18 03:46 UTC, acarrou commented
Still need to edit this. Will complete it tomorrow

2022-01-19 05:21 UTC, naterpotatoers approved these changes
talked with Khalil about using encoder position apparently this solution would not work as it's not truly a fixed position. He spoke with manufacturer a ton prior to buying these and wanted clarification whether we could home using just the device by itself but that is not the case. With that said we can still see what values this prints out but also we should look into homing using mission control. Maybe we could home it with mission control making small adjustments on each wheel somehow i don't know how complicated that would be but it sounds like we might be able to repurpose the singular wheel modes for this in the meantime.

2022-01-19 05:35 UTC, acarrou commented
> talked with Khalil about using encoder position apparently this solution would not work as it's not truly a fixed position. He spoke with manufacturer a ton prior to buying these and wanted clarification whether we could home using just the device by itself but that is not the case. With that said we can still see what values this prints out but also we should look into homing using mission control. Maybe we could home it with mission control making small adjustments on each wheel somehow i don't know how complicated that would be but it sounds like we might be able to repurpose the singular wheel modes for this in the meantime.

Ah darn, that's annoying. Usually, with these motors, the encoder position is super helpful :/ I can try and come up with another solution. Thanks for letting me know @naterpotatoers

2022-01-19 05:35 UTC, merged