Hand setters getter
SJSURoboticsTeam/urc-control_systems-2021 pull request #113
Opened 2022-01-16 02:54 UTC by Mchan2003

2022-01-17 01:02 UTC, naterpotatoers approved these changes

2022-01-17 01:02 UTC, naterpotatoers commented on Arm/Hand/hand.hpp
>    Hand(sjsu::arm::WristJoint wrist) : wrist_(wrist) {}
```suggestion
  Hand(sjsu::arm::WristJoint & wrist) : wrist_(wrist) {}
```
Try this fix and it should fix errors

2022-01-17 01:18 UTC, naterpotatoers commented
Do not merge until this compiles*** I just approved it out of courtesy since it should be an easy fix

2022-01-17 04:13 UTC, Mchan2003 commented on Arm/Hand/hand.hpp
>    Hand(sjsu::arm::WristJoint wrist) : wrist_(wrist) {}
Hi, I tried to compile the code with your fix but it keeps giving me this error: 

` error: uninitialized reference member in 'class sjsu::RmdX&' [-fpermissive]
   28 | Hand(sjsu::arm::WristJoint & wrist) : wrist_(wrist) {}
      |   ^~~~`

Which reference member is the error referring to?

2022-01-17 20:16 UTC, Mchan2003 commented on Arm/Hand/hand.hpp
>    Hand(sjsu::arm::WristJoint wrist) : wrist_(wrist) {}
Nevermind. I think I solved the error.

2022-01-18 02:18 UTC, naterpotatoers commented on Arm/Hand/hand.hpp
>    Hand(sjsu::arm::WristJoint wrist) : wrist_(wrist) {}
sorry didn't see this earlier

2022-01-19 02:48 UTC, naterpotatoers requested changes
Honestly with the addition of the finger.hpp class we can probably just close out this PR without merging it since we will instead be calling the Finger.hpp class within this class for moving the fingers etc. Sorry about that, probably should have spent more time brainstorming before implementing

2022-01-19 02:48 UTC, naterpotatoers commented on Arm/Hand/hand.hpp
> +    float thumb_angle_   = 0;
Leave the trailing underscore off. Here's the [Google style guide reference](https://google.github.io/styleguide/cppguide.html#Variable_Names)

2022-01-19 02:48 UTC, naterpotatoers commented on Arm/Hand/hand.hpp
>    Hand(sjsu::arm::WristJoint wrist) : wrist_(wrist) {}
We need to pass by reference here still 
```suggestion
  Hand(sjsu::arm::WristJoint & wrist) : wrist_(wrist) {}
```

2022-01-19 02:48 UTC, naterpotatoers commented on Arm/Hand/hand.hpp
> +  };
Since we've implemented the Finger.hpp class these actually will go away and be handled in the Finger.hpp class now

2022-01-19 02:48 UTC, naterpotatoers commented on Arm/Hand/hand.hpp
>    };
As mentioned before, these will be replaced by the finger.hpp class which should be public member variables of this class

2022-01-19 04:48 UTC, closed without merging