Implemented Switchable leg orientation
SJSURoboticsTeam/urc-control_systems-2021 pull request #121
Opened 2022-01-20 19:59 UTC by Maaz0070

2022-01-21 04:22 UTC, naterpotatoers requested changes
@kammce Do you have any ideas for resolving SJSURoboticsTeam/urc-central-2021/issues/167

2022-01-21 04:22 UTC, naterpotatoers commented on Drive/rover_drive_system.hpp
> +  Wheel arrays[3] = {left_wheel_, right_wheel_, back_wheel_};
Was this utilized anywhere?

2022-01-21 04:27 UTC, Maaz0070 commented on Drive/rover_drive_system.hpp
> +  Wheel arrays[3] = {left_wheel_, right_wheel_, back_wheel_};
No. I Forgot to remove it.

2022-01-21 23:34 UTC, naterpotatoers commented
Which files did you directly modify from Dev2? We only need the files you modified. Everything else can be imported from dev2 still

2022-01-21 23:49 UTC, Maaz0070 commented
> 
Since the files I modified included other files, mainly in the util folder, I just added the util folder. Everything outside the util folder are files I modified. 
Ill change it to where we don't import the entire util folder and only the ones we need.

2022-01-23 03:52 UTC, naterpotatoers commented
As per the Discord thread 'Updating Libraries' we can try inheriting the RMD, Gpio, and CAN drivers and adding in our logic changes that way. Also good idea to just rename these drivers to something different

2022-01-25 21:11 UTC, naterpotatoers requested changes
Make sure to fix all the unit tests for drive system so that they all pass

2022-01-25 21:11 UTC, naterpotatoers commented on Drive/rover_drive_system.hpp
> +  void switchLegOrientation(RoverDriveSystem &drive, Wheel &left, Wheel &right, Wheel &back)
Possible Wheel Orientations
Left, Right, Back --> Back, Left, Right --> Right, Back, Left
Back, Left, Right 
Right, Back, Left  
Not Possible Wheel Orientations (inverts drive steer logic)
Left, Back, Right
Right, Right, Right
```suggestion
  void SwitchLegOrientation(RoverDriveSystem &drive, Wheel &left, Wheel &right, Wheel &back)
```

2022-01-25 21:11 UTC, naterpotatoers commented on Drive/rover_drive_system.hpp
> +    if(left_wheel_->GetHubSpeed() == 0 && right_wheel_->GetHubSpeed() == 0 && back_wheel_->GetHubSpeed() == 0)
```suggestion
    if(IsStopped())
```
We have a helper function for this call

2022-01-25 21:11 UTC, naterpotatoers commented on Drive/rover_drive_system.hpp
> +    }
This should never be ran. Our code should be smart enough to stop itself before this function ever gets called imo

2022-01-25 21:11 UTC, naterpotatoers commented on Drive/rover_drive_system.hpp
> +  void switchLegOrientation(int position)
```suggestion
  void SwitchLegOrientation(int position)
```

2022-02-06 01:51 UTC, naterpotatoers commented
Is the PR good to close since other PR got merged with these changes?

2022-02-06 16:08 UTC, Maaz0070 commented
> Is the PR good to close since other PR got merged with these changes?

Yes

2022-02-07 05:31 UTC, closed without merging